import TailwindIndicator from "@/components/tailwind-indicator";
import "./globals.css";
import { Raleway } from "next/font/google";

const raleway = Raleway({ subsets: ["latin"] });

export const metadata = {
    title: "Weather App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={raleway.className}>
                {children}
                <TailwindIndicator />
            </body>
        </html>
    );
}
